#!/bin/bash

aurcnt=$(cower -u | wc -l)
if [ -z $aurcnt ]; then
aurcnt=0
fi

paccnt=$(pacman -Qu | wc -l)
if [ -z $paccnt ]; then
paccnt=0
fi

case "$1" in
p) echo -e $paccnt > /tmp/paccnt
;;
a) echo -e $aurcnt > /tmp/aurcnt
esac
