#!/bin/bash

copy_disc () {
# /dev for drive DVD is located
DEV=sr0

# Disc name (udev)
DVD_NAME=$(udevadm info -n $DEV -q property | sed -n 's/^ID_FS_LABEL=//p')

#copy disc
vobcopy -mvo .tmp/

cd .tmp/$DVD_NAME

INPUT=.
FILE_NAME=$(read -ra lname <<< $(echo ${DVD_NAME,,} | sed 's/_/\ /g')&& echo "${lname[@]^}")
#FILE_NAME=$DVD_NAME
}

if [[ -z "$1" ]]; then

copy_disc

else

INPUT="$1"
FILE_NAME_NOPATH=${1##*/}
FILE_NAME=${FILE_NAME_NOPATH%\.*}
fi

HandBrakeCLI -i "$INPUT" -o /media/Video/"$FILE_NAME.mp4" -Z "Normal" -X 1280 -f mp4 -O -m -5 -N eng --native-dub -s scan,1 --subtitle-default 1 -F
