#!/bin/sh
# install AUR packages with cower

cd /tmp/cower_build && cower -d "$1"
builddir="$_"
cd "$builddir" && ${EDITOR:-vim} PKGBUILD

makepkg -si && cd - &>/dev/null

read -p "Remove Build directory? [Y/n]? " yn
if [ "$yn" = "y" ]; then
    printf "\n%s\n" "Removing build directory..."
    cd ../ && rm -rf "$builddir"
else
    printf "%s\n" "Build completed."
fi

