#!/bin/bash

INTERFACE="eth0"

human_readable ()
{
awk -v x=$1 'BEGIN{

	split("B K M G T P",type)

	for(i=5;y < 1;i--)
	   y = x / (2**(10*i))


	printf "v%.0f",y; print type[i+2]
}'
}

RXB=$(</sys/class/net/$INTERFACE/statistics/rx_bytes)
sleep 1
RXBN=$(</sys/class/net/$INTERFACE/statistics/rx_bytes)
RXDIF=$(echo $((RXBN - RXB)) )

echo -e $(human_readable $RXDIF)
