#!/bin/bash

INTERFACE="wlp3s0"

human_readable ()
{
awk -v x=$1 'BEGIN{

        split("B K M G T P",type)

	for(i=5;y < 1;i--)
	    y = x / (2**(10*i))

	printf "^\%.0f",y; print type[i+2]
}'
}

TXB=$(</sys/class/net/$INTERFACE/statistics/tx_bytes)
sleep 1 
TXBN=$(</sys/class/net/$INTERFACE/statistics/tx_bytes)
TXDIF=$(echo $((TXBN - TXB)) )

if [ -z $(human_readable $TXDIF) ];then
echo "^0B"
else
echo -e $(human_readable $TXDIF)
fi
